### PR TITLE
feat: support signal rest api notifications

### PR DESCRIPTION
**Pull request by MrRagga-**
Hi,
I created a notification for https://github.com/bbernhard/signal-cli-rest-api 
If you are interested in this notification I can finish the missing things like documentation, enhance code, etc...?

### CODE REVIEW

**Comment by MrRagga-** [comment]
Any objections?

**Comment by crazy-max** [comment]
If I understand correctly, this notification will be sent to the https://github.com/bbernhard/signal-cli-rest-api service and then be sent to Signal itself? If so I would be prefer to not use this intermediate service and directly send the notification to Signal.

Also looking at signal-cli-rest-api it looks like you can directly use the [`webhook` notifier](https://crazymax.dev/diun/notif/webhook/).

**Comment by MrRagga-** [comment]
This rest API is just a small wrapper around https://github.com/AsamK/signal-cli which is a binary to talk with the Signal API, which has all the stuff implemented.
I already tried the webhook. But it currently does not support POST requests and not customer payload data.
Thus I can't use it right know.
On the other hand, isn't everything a webhook? I thought to have a more precise plugin might make more sense. But it is your project. I am also willing to modify the webhook to fit needs. Up to you?

**Comment by crazy-max** [comment]
> This rest API is just a small wrapper around https://github.com/AsamK/signal-cli which is a binary to talk with the Signal API, which has all the stuff implemented.

I see that the official https://github.com/signalapp/libsignal doesn't have the Go implementation/binding unfortunately. I found some custom implementations https://libs.garden/go/search?q=libsignal but looks not well maintained. Maybe the C part of the Swift bindings could be used from Go as well but would need to have it on another repo first.

> I already tried the webhook. But it currently does not support POST requests and not customer payload data.
> Thus I can't use it right know.

Ah indeed we can't customize the payload atm.

> On the other hand, isn't everything a webhook? I thought to have a more precise plugin might make more sense. But it is your project. I am also willing to modify the webhook to fit needs. Up to you?

Yes feel free to open another PR to be able to send a custom payload for the webhook notifier and we can take a look here if it fits your needs or requires a dedicated notifier.

**Comment by MrRagga-** [comment]
I already tried to modify the custom webhook, but since I am not very familar with golang, I struggled what the best way is to support any abritary json data. Therefore I went with the native signal implementation, which was much easier. But if you can give me any pointer how to do it, I can submit a PR for the webhook, too.

**Comment by MrRagga-** [comment]
The signal rest-api is quite a famous solution to use for Signal, e.g. https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/Signal.vue and https://www.home-assistant.io/integrations/signal_messenger/ both recommend to use it.

**Comment by crazy-max** [comment]
> I already tried to modify the custom webhook, but since I am not very familar with golang, I struggled what the best way is to support any abritary json data.

I will take a look and open a PR that's fine.

> The signal rest-api is quite a famous solution to use for Signal, e.g. https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/Signal.vue and https://www.home-assistant.io/integrations/signal_messenger/ both recommend to use it.

I see, then I'm ok with this notifier if you can add some docs. I will review after that.

**Comment by MrRagga-** [comment]
I added docs. Feel free to review and leave comments.

**Pull request merged**
