### PR TITLE
Add cli to interact with Diun through gRPC

### LINKED ISSUE #138: Command to list all the images from diun.db that are being checked
Hi,

Firstly, thank you for the project - it's my most useful container! 👍

I was wondering if it was possible to implement the ability to list all the images that are present in diun.db - possibly by running a command on the running container like:

```
docker exec diuncontainer diun --list
```

Alternatively, I tried copying the diun.db file out and opening it in a SQLite browser but it wanted a passphrase to unlock the database - is this passphrase something that can be configured, or can I see where it is?

Thanks!

### PR DESCRIPTION
**Pull request by crazy-max**
Fixes #138
Closes #367

This PR adds a gRPC server to listen for requests from clients and dispatch them to the right service implementation. This will be used to allow concurrent access to the bbolt database through a simple cli. This requires a change in the diun cli to identify the server and cli part.

```
$ diun --help
Usage: diun <command>

Docker image update notifier. More info: https://github.com/crazy-max/diun

Flags:
  -h, --help       Show context-sensitive help.
      --version

Commands:
  serve            Start Diun server.
  image list       List images in database.
  image inspect    Display information of an image in database.
  image remove     Remove an image manifest from database.
  notif test       Test notification settings.

Run "diun <command> --help" for more information on a command.
```

Run "diun <command> --help" for more information on a command.

To run Diun server:

```
$ diun serve --config ./diun.yml
```

An example to list images in the bbolt db:

```
$ diun image list
+---+---------------------------------+---------+----------------------+-------------------------------------------------------------------------+
| # | NAME                            | TAG     | UPDATED              | DIGEST                                                                  |
+---+---------------------------------+---------+----------------------+-------------------------------------------------------------------------+
| 0 | docker.io/crazymax/diun         | edge    | 2021-05-11T11:08:25Z | sha256:56264f6bf7e07ec34ac5ab0488d8705a3e1e41900cc5fb173d78569fb487db69 |
| 1 | docker.io/crazymax/docker       | 20.10.6 | 2021-04-22T22:21:26Z | sha256:9ed9d39113a09f6609299af01023cf19b6633575ca39322cf448c45bc9cc3433 |
| 2 | docker.io/crazymax/yasu         | edge    | 2021-04-04T21:47:17Z | sha256:880da7a0476c78c23fcb6dda31ba8984a71e163ac95fc93e71a88b4b80b3d313 |
| 3 | docker.io/library/alpine        | latest  | 2021-04-14T19:19:39Z | sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f |
+---+---------------------------------+---------+----------------------+-------------------------------------------------------------------------+
```

cc @Vorsku @richardneish

### CODE REVIEW

**Comment by richardneish** [comment]
I love it!  One initial impression, for easier migration from the current version, would it be possible to make "diun serve" the default behaviour if no command is given?

**Comment by crazy-max** [comment]
@richardneish 

> would it be possible to make "diun serve" the default behaviour if no command is given?

I can do that with subcommands but don't think it works top commands with the actual parser.

**Comment by richardneish** [comment]
> @richardneish
> 
> > would it be possible to make "diun serve" the default behaviour if no command is given?
> 
> I can do that with subcommands but don't think it works with top commands with the actual parser.

OK, I guess it's not needed since we will run that from the Dockerfile, so it will still be a straightforward upgrade.  Looks good to me!

**Comment by crazy-max** [comment]
@richardneish 

> OK, I guess it's not needed since we will run that from the Dockerfile, so it will still be a straightforward upgrade. Looks good to me!

Yes that's it and just in case I have added a tiny upgrade notes: https://github.com/crazy-max/diun/pull/382/commits/87678a46e994f93a5636b0c690cabf70cd5178cc

**Pull request merged**
