### PR TITLE
telegram: add topics support

### PR DESCRIPTION
**Pull request by crazy-max**
fixes https://github.com/crazy-max/diun/issues/948
closes #1125
closes #1305

Carry changes from https://github.com/crazy-max/diun/pull/1125 but merge topics within `chatIDs` with a specific format and add tests.

cc @jon4hz @bytebone

### CODE REVIEW

**Comment by bytebone** [comment]
Looks good after a quick skim without doing my own tests. Thanks for doing the final steps, I'll happily close my PR and branch once this merges.

**Comment by chris-1243** [comment]
sorry to jump in, since latest version (4.29.0), I have now this error and I am unable to use Telegram notification

```
diun: error: rpc error: code = Unknown desc = cannot parse chat IDs for Telegram notifier: invalid chat ID x.xxxxxxxxxe+09 (type=float64)
``` 

I guess it might be related to this PR. Any advices on how to solve the issue?

**Comment by bytebone** [comment]
> ```
> diun: error: rpc error: code = Unknown desc = cannot parse chat IDs for Telegram notifier: invalid chat ID x.xxxxxxxxxe+09 (type=float64)
> ```

It might not have been made clear enough on the update - the telegram chat ID was changed from a number to a string. So you need to enclose it with double quotes in your config:
```diff
notif:
  telegram:
    token: aabbccdd:11223344
    chatIDs:
-      - 123456789
+      - "123456789"
```
More examples are [in the docs](https://crazymax.dev/diun/notif/telegram/). I hope this helps.

**Comment by chris-1243** [comment]
Thanks for your answer.

Effectively, double quotes are needed. I edited my secret file and now everything is working.

I would maybe edit this part of the documentation as double quotes are not used if you do not specify a target message topic.

Untitled

**Comment by crazy-max** [comment]
@chris-1243 Do you have this issue through `chatIDsFile` or `chatIDs` option?

**Comment by chris-1243** [comment]
I had the issue through `DIUN_NOTIF_TELEGRAM_CHATIDSFILE` env variable in `docker-compose.yaml`.

I tried `DIUN_NOTIF_TELEGRAM_CHATIDS` and the same error was displayed.

In both case, the use of the double quotes is required

**Pull request merged**
